defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base
  - message_provider/empty@initial_message_provider
  - message_provider/synthetic_messages/short_news_10@recurrent_message_provider
  - clustering: hac
  - embedding: e5

project_path: ${user_settings.project_path}
dataset_path: ${user_settings.dataset_path}
model_path: ${user_settings.model_path}
result_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}

output:
  summary_path: ${result_dir}/summary.csv
  clustering_json_path: ${result_dir}/clustering_results.json

message_handlers:
  - _target_: kygs.message_handler.MessageJsonSaver
    output_path: ${output.clustering_json_path}
