defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base

project_path: ${user_settings.project_path}
dataset_path: ${user_settings.dataset_path}
model_path: ${user_settings.model_path}
result_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}

message_datasets_to_merge:
  - ${dataset_path}/synthetic_messages/medium_news_1000/news_dataset.csv
  - ${dataset_path}/synthetic_messages/medium_texting_1000/human_messages_dataset.csv

output_dataset_path: ${dataset_path}/synthetic_messages/medium_texting_and_news_2000/medium_texting_and_news_2000.csv
drop_text_duplicates: true
