_target_: kygs.clustering.hac.HacBasedTextClustering
_recursive_: True
text_embedding_model: ${embedding}
distance_threshold: 0.1
cluster_collection:
  _target_: kygs.clustering.hac.FullEmbeddingClusterListCollection
linkage: average
